FROM node:20-alpine AS base
WORKDIR /app
RUN corepack enable

FROM base AS deps
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile --ignore-scripts

FROM base AS builder
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ARG NODE_ENV=production
ARG NEXT_PUBLIC_APP_URL=http://localhost:3000
ARG DATABASE_URL
ARG GEMINI_API_KEY
ARG GEMINI_IMAGE_MODEL=gemini-2.5-flash-image
ARG CRON_SECRET
ARG ADMIN_API_TOKEN
ARG APP_ENCRYPTION_KEY
ARG KEYWORDS_PER_NICHE=4
ARG COMPARISON_KEYWORDS_PER_NICHE=2
ARG BLOG_GENERATION_BATCH_SIZE=8
ARG AUTO_PUBLISH_GENERATED_POSTS=true
ARG BLOG_GENERATION_SCHEDULE="0 2 * * *"
ARG METRICS_UPDATE_SCHEDULE="0 6 * * *"
ARG TECH_NEWS_SCHEDULE="0 */2 * * *"
ARG CONTENT_REFRESH_SCHEDULE="30 6 * * 1"
ARG CONTENT_REFRESH_BATCH_SIZE=4
ARG CONTENT_REFRESH_MIN_IMPRESSIONS=200
ARG CONTENT_REFRESH_MAX_CTR=2.5
ARG CONTENT_REFRESH_MIN_POSITION=14
ARG CONTENT_REFRESH_MIN_AGE_DAYS=14
ARG DEFAULT_TENANT_ID
ARG DEFAULT_WEBSITE_ID
ARG GSC_SITE_URL
ARG GOOGLE_SEARCH_CONSOLE_ACCESS_TOKEN
ARG GOOGLE_OAUTH_CLIENT_ID
ARG GOOGLE_OAUTH_CLIENT_SECRET
ARG GOOGLE_OAUTH_REDIRECT_URI
ARG EXTERNAL_PUBLISH_WEBHOOK_URL
ARG EXTERNAL_PUBLISH_WEBHOOK_SECRET
ARG CONTENT_API_KEY

ENV NODE_ENV=$NODE_ENV \
    NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL \
    DATABASE_URL=$DATABASE_URL \
    GEMINI_API_KEY=$GEMINI_API_KEY \
    GEMINI_IMAGE_MODEL=$GEMINI_IMAGE_MODEL \
    CRON_SECRET=$CRON_SECRET \
    ADMIN_API_TOKEN=$ADMIN_API_TOKEN \
    APP_ENCRYPTION_KEY=$APP_ENCRYPTION_KEY \
    KEYWORDS_PER_NICHE=$KEYWORDS_PER_NICHE \
    COMPARISON_KEYWORDS_PER_NICHE=$COMPARISON_KEYWORDS_PER_NICHE \
    BLOG_GENERATION_BATCH_SIZE=$BLOG_GENERATION_BATCH_SIZE \
    AUTO_PUBLISH_GENERATED_POSTS=$AUTO_PUBLISH_GENERATED_POSTS \
    BLOG_GENERATION_SCHEDULE=$BLOG_GENERATION_SCHEDULE \
    METRICS_UPDATE_SCHEDULE=$METRICS_UPDATE_SCHEDULE \
    TECH_NEWS_SCHEDULE=$TECH_NEWS_SCHEDULE \
    CONTENT_REFRESH_SCHEDULE=$CONTENT_REFRESH_SCHEDULE \
    CONTENT_REFRESH_BATCH_SIZE=$CONTENT_REFRESH_BATCH_SIZE \
    CONTENT_REFRESH_MIN_IMPRESSIONS=$CONTENT_REFRESH_MIN_IMPRESSIONS \
    CONTENT_REFRESH_MAX_CTR=$CONTENT_REFRESH_MAX_CTR \
    CONTENT_REFRESH_MIN_POSITION=$CONTENT_REFRESH_MIN_POSITION \
    CONTENT_REFRESH_MIN_AGE_DAYS=$CONTENT_REFRESH_MIN_AGE_DAYS \
    DEFAULT_TENANT_ID=$DEFAULT_TENANT_ID \
    DEFAULT_WEBSITE_ID=$DEFAULT_WEBSITE_ID \
    GSC_SITE_URL=$GSC_SITE_URL \
    GOOGLE_SEARCH_CONSOLE_ACCESS_TOKEN=$GOOGLE_SEARCH_CONSOLE_ACCESS_TOKEN \
    GOOGLE_OAUTH_CLIENT_ID=$GOOGLE_OAUTH_CLIENT_ID \
    GOOGLE_OAUTH_CLIENT_SECRET=$GOOGLE_OAUTH_CLIENT_SECRET \
    GOOGLE_OAUTH_REDIRECT_URI=$GOOGLE_OAUTH_REDIRECT_URI \
    EXTERNAL_PUBLISH_WEBHOOK_URL=$EXTERNAL_PUBLISH_WEBHOOK_URL \
    EXTERNAL_PUBLISH_WEBHOOK_SECRET=$EXTERNAL_PUBLISH_WEBHOOK_SECRET \
    CONTENT_API_KEY=$CONTENT_API_KEY

# Use webpack build path for more predictable CI/container builds.
RUN pnpm exec prisma generate && pnpm exec next build --webpack

FROM base AS runner
ENV NODE_ENV=production

ARG NEXT_PUBLIC_APP_URL=http://localhost:3000
ARG DATABASE_URL
ARG GEMINI_API_KEY
ARG GEMINI_IMAGE_MODEL=gemini-2.5-flash-image
ARG CRON_SECRET
ARG ADMIN_API_TOKEN
ARG APP_ENCRYPTION_KEY
ARG KEYWORDS_PER_NICHE=4
ARG COMPARISON_KEYWORDS_PER_NICHE=2
ARG BLOG_GENERATION_BATCH_SIZE=8
ARG AUTO_PUBLISH_GENERATED_POSTS=true
ARG BLOG_GENERATION_SCHEDULE="0 2 * * *"
ARG METRICS_UPDATE_SCHEDULE="0 6 * * *"
ARG TECH_NEWS_SCHEDULE="0 */2 * * *"
ARG CONTENT_REFRESH_SCHEDULE="30 6 * * 1"
ARG CONTENT_REFRESH_BATCH_SIZE=4
ARG CONTENT_REFRESH_MIN_IMPRESSIONS=200
ARG CONTENT_REFRESH_MAX_CTR=2.5
ARG CONTENT_REFRESH_MIN_POSITION=14
ARG CONTENT_REFRESH_MIN_AGE_DAYS=14
ARG DEFAULT_TENANT_ID
ARG DEFAULT_WEBSITE_ID
ARG GSC_SITE_URL
ARG GOOGLE_SEARCH_CONSOLE_ACCESS_TOKEN
ARG GOOGLE_OAUTH_CLIENT_ID
ARG GOOGLE_OAUTH_CLIENT_SECRET
ARG GOOGLE_OAUTH_REDIRECT_URI
ARG EXTERNAL_PUBLISH_WEBHOOK_URL
ARG EXTERNAL_PUBLISH_WEBHOOK_SECRET
ARG CONTENT_API_KEY

ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL \
    DATABASE_URL=$DATABASE_URL \
    GEMINI_API_KEY=$GEMINI_API_KEY \
    GEMINI_IMAGE_MODEL=$GEMINI_IMAGE_MODEL \
    CRON_SECRET=$CRON_SECRET \
    ADMIN_API_TOKEN=$ADMIN_API_TOKEN \
    APP_ENCRYPTION_KEY=$APP_ENCRYPTION_KEY \
    KEYWORDS_PER_NICHE=$KEYWORDS_PER_NICHE \
    COMPARISON_KEYWORDS_PER_NICHE=$COMPARISON_KEYWORDS_PER_NICHE \
    BLOG_GENERATION_BATCH_SIZE=$BLOG_GENERATION_BATCH_SIZE \
    AUTO_PUBLISH_GENERATED_POSTS=$AUTO_PUBLISH_GENERATED_POSTS \
    BLOG_GENERATION_SCHEDULE=$BLOG_GENERATION_SCHEDULE \
    METRICS_UPDATE_SCHEDULE=$METRICS_UPDATE_SCHEDULE \
    TECH_NEWS_SCHEDULE=$TECH_NEWS_SCHEDULE \
    CONTENT_REFRESH_SCHEDULE=$CONTENT_REFRESH_SCHEDULE \
    CONTENT_REFRESH_BATCH_SIZE=$CONTENT_REFRESH_BATCH_SIZE \
    CONTENT_REFRESH_MIN_IMPRESSIONS=$CONTENT_REFRESH_MIN_IMPRESSIONS \
    CONTENT_REFRESH_MAX_CTR=$CONTENT_REFRESH_MAX_CTR \
    CONTENT_REFRESH_MIN_POSITION=$CONTENT_REFRESH_MIN_POSITION \
    CONTENT_REFRESH_MIN_AGE_DAYS=$CONTENT_REFRESH_MIN_AGE_DAYS \
    DEFAULT_TENANT_ID=$DEFAULT_TENANT_ID \
    DEFAULT_WEBSITE_ID=$DEFAULT_WEBSITE_ID \
    GSC_SITE_URL=$GSC_SITE_URL \
    GOOGLE_SEARCH_CONSOLE_ACCESS_TOKEN=$GOOGLE_SEARCH_CONSOLE_ACCESS_TOKEN \
    GOOGLE_OAUTH_CLIENT_ID=$GOOGLE_OAUTH_CLIENT_ID \
    GOOGLE_OAUTH_CLIENT_SECRET=$GOOGLE_OAUTH_CLIENT_SECRET \
    GOOGLE_OAUTH_REDIRECT_URI=$GOOGLE_OAUTH_REDIRECT_URI \
    EXTERNAL_PUBLISH_WEBHOOK_URL=$EXTERNAL_PUBLISH_WEBHOOK_URL \
    EXTERNAL_PUBLISH_WEBHOOK_SECRET=$EXTERNAL_PUBLISH_WEBHOOK_SECRET \
    CONTENT_API_KEY=$CONTENT_API_KEY

COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/next.config.mjs ./next.config.mjs

EXPOSE 3000
CMD ["pnpm", "start"]
